shell /home/linuxbrew/.linuxbrew/bin/fish

# vim:fileencoding=utf-8:foldmethod=marker
include theme.conf

enable_audio_bell no
window_alert_on_bell no

#Fonts
#font_family FiraCode Nerd Font
font_family Maple Mono NF
# font_family JetBrains Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12
enable_ligatures always

# Cursor: blinking block
cursor_shape block
cursor_blink_interval 0.5
cursor_shape_unfocused hollow
shell_integration no-cursor

# url
detect_urls yes
# url_color #ffff00
url_style straight
open_url_with default

# Theme
# background #1b1b27
# selection_background #ffffff
background_opacity 0.98

#dynamic_background_opacity yes
background_blur 1 
#active_border_color #7AA2F7
#inactive_border_color #000000
#window padding
window_padding_width 3
window_padding_height 3

# Window borders (block style)
border_width 2pt
active_border_color #7AA2F7
inactive_border_color #3b4248

# tabs
tab_bar_edge top
tab_bar_margin_width 1.0
tab_bar_margin_height 1.0 0.5
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}"

# styling tabs
#active_tab_foreground #0da38a 
#active_tab_background #1d202f
#active_tab_font_style bold-italic
#inactive_tab_foreground #ffffff
#inactive_tab_background #292945
#inactive_tab_font_style normal

# clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# keymaps
map ctrl+shift+i next_layout
map ctrl+shift+enter new_window
map ctrl+shift+l next_window
map ctrl+shift+h previous_window

map ctrl+t new_tab
map ctrl+shift+w close_tab

map ctrl+shift+r load_config_file
map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /bin/sh -c 'fzf --no-sort --no-mouse --exact -i --tac | tr -d "\n" | kitty +kitten clipboard'


